kakaopay:
  base-url: https://open-api.kakaopay.com
  secret-key: ${KAKAOPAY_SECRET_KEY_DEV:__MISSING__}
  authorization-prefix: "SECRET_KEY "
  cid: "TC0ONETIME"
  ready-path: "/online/v1/payment/ready"
  approve-path: "/online/v1/payment/approve"
  cancel-path: "/online/v1/payment/cancel"
  approval-url: "http://localhost:8080/api/payments/{paymentId}/approve"
  cancel-url: "http://localhost:8080/api/payments/{paymentId}/cancel"
  fail-url: "http://localhost:8080/api/payments/{paymentId}/fail"
